import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';

// Build-time helper: embed outscraper-api-docs.json into a TS module.
// This makes the runtime server independent from the JSON file presence.

const INPUT = 'outscraper-api-docs.json';
const OUTPUT = 'src/outscraperApiDocs.generated.ts';

const jsonText = await readFile(INPUT, 'utf8');
const doc = JSON.parse(jsonText);

// Keep output deterministic.
const embedded = JSON.stringify(doc, null, 2);

const banner = `/* eslint-disable */
/* AUTO-GENERATED FILE. DO NOT EDIT.
   Generated by scripts/embed-openapi.mjs from ${INPUT}
*/
`;

const out = `${banner}
export const embeddedOpenApiDocument = ${embedded} as const;
`;

await mkdir(dirname(OUTPUT), { recursive: true });
await writeFile(OUTPUT, out, 'utf8');
console.log(`Embedded OpenAPI spec written to ${OUTPUT}`);
